name: Publish to pypi

on:
  release:
    types: [released]
permissions:
  contents: read
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/neomaril-codex
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build
      working-directory: ./
      run: |
        python setup.py sdist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
          packages-dir: dist/
          skip-existing: true
          verbose: true