name: Sphinx build
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    permissions:
      id-token: write
      contents: write
      deployments: write
      pages: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install pydata-sphinx-theme==0.12.0 sphinx==6.1.3 m2r2
          pip install -r requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './_build/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
